### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by mattkanwisher** [dgryski/go-tsz#18]
add a license so others can potentially reuse this. Thanks a bunch

**Comment by hnakamur** [comment]
First of all, thanks for implementing and sharing a nice software!

I'd like to use this so could you add a license please?
I hope you choose a permissive license like MIT or BSD.
Thanks!

**Comment by hnakamur** [comment]
I created my own library since I would like different APIs.
https://github.com/hnakamur/timeseries
The implementation is based on https://github.com/burmanm/gorilla-tsc/ (Apache 2 lcense).

My library depends on @dgryski 's Go bit stream library https://github.com/dgryski/go-bitstream (MIT license).
Thanks for a nice library!

**Comment by dgryski** [comment]
Oops, sorry.  I didn't see this issue.  I'll push an MIT license tonight or tomorrow.
